### ISSUE TITLE
MethodBinding doesn't work in EventSetter?

### ISSUE THREAD

**Issue by this-is-your-do** [Singulink/Singulink.WPF.Data.MethodBinding#3]
If I do something like this:
```
        <ListView.ItemContainerStyle>
            <Style TargetType="{x:Type ListViewItem}">
                <EventSetter Event="MouseDoubleClick" Handler="{s:MethodBinding Activate}" />
            </Style>
        </ListView.ItemContainerStyle>
```
A null reference exception is thrown when the xaml is first loaded.
Is this an inherent limitation of xaml, or something that can be fixed?

(I'm using .NET 5)

**Comment by mikernet** [comment]
I will have to trace this particular usage to see what is going on. It probably needs to be special-cased for `EventSetter` use. I will have a look in the next couple days.

**Comment by mikernet** [comment]
As far as I can tell, it doesn't look like you can use any markup extensions in `EventSetter`, and it appears as though this is a limitation of the XAML parser for some reason. I don't get a null reference exception but rather a XAML parse exception when I try to do this and the markup extension is never instantiated.

I'll post an issue in the WPF repo to see what they say there.

**Comment by mikernet** [comment]
WPF repo issue reference: https://github.com/dotnet/wpf/issues/5353

**Comment by this-is-your-do** [comment]
Thanks!

**Comment by mikernet** [comment]
Going to close this as it is a WPF limitation as per the linked issue. If that situation changes then we can revisit this.
