### ISSUE TITLE
How to specify ElementName.DataContext for MethodBinding

### ISSUE THREAD

**Issue by wf-soft** [Singulink/Singulink.WPF.Data.MethodBinding#5]
DataContext cannot be specified in a hierarchical Datatemplate or Datatemplate. The target will be inflexible

**Comment by mikernet** [comment]
Please elaborate with an example of what the issue is and/or what you hope to achieve.

**Comment by mikernet** [comment]
I'm going to close this issue for now, but feel free to respond if you still have a problem.
